"""add activity and stay contact/location fields

Revision ID: 62e087d4586b
Revises: ef6fd988963c
Create Date: 2026-08-13 10:19:28.761098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e087d4586b'
down_revision: Union[str, Sequence[str], None] = 'ef6fd988963c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('map_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('map_link')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
