"""add category sort_order

Revision ID: 8c995f8de228
Revises: d389af05532a
Create Date: 2026-08-21 09:33:50.191474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c995f8de228'
down_revision: Union[str, Sequence[str], None] = 'd389af05532a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Backfill: give existing categories a real sort_order matching their
    # current display order (alphabetical by name, the old get_categories
    # ordering) rather than leaving them all at the server_default of 0 -
    # otherwise every category would tie at 0 and "sort by category" would
    # fall back to whatever arbitrary order SQLite happens to return ties
    # in, not the order Manage Categories was already showing them in.
    categories = sa.table("categories", sa.column("id", sa.Integer), sa.column("name", sa.String), sa.column("sort_order", sa.Integer))
    conn = op.get_bind()
    rows = conn.execute(sa.select(categories.c.id).order_by(categories.c.name)).fetchall()
    for index, row in enumerate(rows):
        conn.execute(categories.update().where(categories.c.id == row.id).values(sort_order=(index + 1) * 10))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
