"""add city to trip and activity

Revision ID: a43969de6e91
Revises: 8c995f8de228
Create Date: 2026-08-25 09:47:30.386622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43969de6e91'
down_revision: Union[str, Sequence[str], None] = '8c995f8de228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('city')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
