"""add cost to stay

Revision ID: a554e3cc5220
Revises: fddb6362a081
Create Date: 2026-08-28 14:51:58.683654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a554e3cc5220'
down_revision: Union[str, Sequence[str], None] = 'fddb6362a081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
