"""add activity distance cache

Revision ID: fddb6362a081
Revises: a43969de6e91
Create Date: 2026-08-25 10:36:08.244821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddb6362a081'
down_revision: Union[str, Sequence[str], None] = 'a43969de6e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_activity_id', sa.Integer(), nullable=False),
    sa.Column('destination_activity_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('distance_text', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_text', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['origin_activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_activity_id', 'destination_activity_id', 'mode', name='uq_activity_distance_pair_mode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_distances')
    # ### end Alembic commands ###
